### ISSUE TITLE
✨TinaCMS | Fix TailWind Start Template for localhost (Dev Experience)

### ISSUE THREAD

**Issue by Dhruv-0987** [tinacms/tina.io#1728]
CC: @wicksipedia  @Levijj22
Context: https://youtu.be/uJde9cz24ww?t=51&si=G3lp05FstWhGIGdp 

### 🩸Pain:
When trying to use the 'Tailwind Starter' startup template, a series of errors ensue. This makes it more difficult for users to first experience using Tina CMS, requires more experienced developers to get it running locally. 

### 💡 Suggested Solution:
Firstly, either the broken starter template should be removed from the options or a custom message should prompt users after picking 'Tailwind Starter' that this is broken and to use another template until it is fixed. 

++ look into future proofing 

Then, the dependency errors should be addressed, fixing the version conflicts so that the 'Tailwind Starter' template is useable. 

### 💼 Tasks
- [x] Either remove the Tailwind Starter option from template options OR input a custom message prompting users this template is broken at the moment and to use other templates. 
- [x] Investigate dependency conflicts with the Tailwind Starter
- [x] Fix dependency version conflicts
- [x] Test 
- [x] Create a PR 

### ✅ Acceptance Criteria 
- [x] The Tailwind Starter template successfully generates app without any dependency conflicts
- [ ] Investigate future proofing out-dated dependencies  

### 📸 Screenshots 
<img width="579" alt="Screenshot 2024-04-26 at 11 09 24 am" src="https://github.com/tinacms/tina.io/assets/137844305/1ff8f5f3-5b34-4d22-a7e8-65b40bc51c61">

**Figure: ❌ Current Errors Associated with using Tailwind Starter Template**

**Comment by 2fernandez** [comment]
Customer journeys are a well-documented UX process, easy to learn and adapt in about 10 mins. 

Customer Journeys - do not typically start on websites
The video jumped right into Onboarding, which is almost the last step of a customer journey.

**Comment by 2fernandez** [comment]
Customer journeys do not typically start on the website. 
The video starts of on the 2nd step of a customer journey which is the "Explore" phase
And then jumps right into the "Onboarding", almost the last step of a customer journey.

**Comment by joshbermanssw** [comment]
Update: PR has been created in the tina-cloud-starter repo : https://github.com/tinacms/tina-cloud-starter/pull/507

**Comment by joshbermanssw** [comment]
❌ Blocked: Awaiting PR approval

**Comment by joshbermanssw** [comment]
<img width="610" alt="Screenshot 2024-05-08 at 3 51 17 pm" src="https://github.com/tinacms/tina.io/assets/137844305/96b0dc54-13ef-42ee-820e-ba32909d53e0">

**Figure: No more errors when using the Tailwind starter template!** 


Closing issue - error fixed.
