### ISSUE TITLE
👔 Pricing Model | Improve Model Perks + Reduce Gaps Between Tiers.

### ISSUE THREAD

**Issue by Dhruv-0987** [tinacms/tina.io#1733]
### 🩸 Pain

Currently there are four tiers with large gaps in price between them, making it hard for users to find a plan that fits their needs. Within these tiers, there is not a clear description of some of the perks at the forefront of the selling points (i.e users and roles). 

The actual pricing page itself does not compare the actual differences between each tier, just advertises what that tier itself provides. 

### 💡 Suggested Solution
To revamp the pricing model to rather use per-user pricing instead of per-project pricing, this will make estimations easier. There also should be a distinction in tiers based upon features needed rather than number of projects (as this number is hard to estimate)

The websites pricing page should clearly compare the tiers against one another, highlighting the benefit of upgrading tiers.

Also add more benefits of how it compares to competitors

### 💼 Tasks 

- [ ] TBD by business
- [ ] The pricing model to be updated to a per-user pricing model and conveyed on the website
- [ ] The tier differentiation is to be based off of features rather than number of projects and this is conveyed on the website
- [ ] The website pricing page clearly compares the tiers against one another in a comparison table. 

### ✅ Acceptance Criteria 

- [ ] The tasks are complete 

### ➕ More Information

Pain points from Customer Journey video - https://youtu.be/uJde9cz24ww?t=1233

### 📸 Screenshots 

Cc:

**Comment by Marxoz** [comment]
Already Done
