### ISSUE TITLE
✨ Tina.io | Sample Templates and Showing off Tina Features

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#1743]
### 🩸 Pain

Currently when users go to try out TinaCMS locally there is very little promotion of what TinaCMS actually provides and its capabilities with examples. This is a huge miss of a selling point. 

### 💡 Suggested Solution

Within templates there should be examples of what TinaCMS can do by providing numerous examples of its capabilities. This can be accompanied by a link to a developer demo-ing TinaCMS from the same template. There also should be links to support pages/ forums (i.e Discord) on the template. 

### 💼 Tasks 

- [ ] Agree upon chosen capabilities to display on template
- [ ] Implement the generic features to the template homepage
- [ ] Record a demo video of a developer running through features of Tina and where to go from the template (Needs to be approved by Adam) 
- [ ] Display video on template homepage 
- [ ] Include support pages / links to the template homepage

### ✅ Acceptance Criteria 

- [ ] All tasks are completed 

### ➕ More Information

https://youtu.be/uJde9cz24ww?t=422 - Pain point from CTF review

### 📸 Screenshots 

![Screenshot 2024-04-26 at 12 39 11 pm](https://github.com/tinacms/tina.io/assets/137844305/f1b75877-f167-4d73-9b1d-8ee488e1fa2a)
**Figure: Mock-up of example template homepage from Levi's Video** 

Cc:
