### ISSUE TITLE
⚒️ Tina.io | SSWCodeAuditor Improvements

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#1744]
### 🩸 Pain
[CodeAuditor ](https://codeauditor.com/) has revealed underlying performance issues - please see the audit at [SSW Internal Sharepoint](https://sswcom.sharepoint.com/SitePages/Internal-Projects.aspx)

### 💡 Suggested Solution
Use the audit as a guide to tackle inefficient metrics, and improve the performance of the site. 

### 💼 Tasks 

- [x] Review, and fix (or remove) broken links 
- [x] Fix mix-matched attribute names 
- [x] Review, and fix URLS with full-stop / "/" at the end 
- [ ] Review, and improve the largest contentful paint 
- [ ] Review, and improve the total blocking time 
- [ ] Review, and improve the speed index
- [ ] Mark unused JavaScript for deletion 
- [ ] Once reviewed, remove unused JavaScript 
- [ ] Defer offscreen imaging
- [ ] Re-run SSWCodeAuditor on tina.io 

### ✅ Acceptance Criteria 

- [ ] Improve overall performance metric shown in code auditor 
- [x] Reduce broken links 
- [x] Reduce code errors and warnings

### 📸 Screenshots 

Cc:
