### ISSUE TITLE
✨ Tina.io | Site Chat-Bot

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#1748]
### 🩸 Pain

Currently, there are buttons on the home-page (like the sign-up) that are not awfully descriptive, and the flow of support for simple questions on the home-page is time consuming (i.e users must go through discord) 

### 💡 Suggested Solution

As a part of the [user experience epic/issue](https://github.com/tinacms/tina.io/issues/1731), implement a chat-bot on the Tina site that will help users with simple queries 

### 💼 Tasks 

- [x] Speak to the chat-bot team that implemented sophie-bot
- [x] Look into alternatives of chatbase 
- [x] Spin up chat-bot prompts 
- [x] Work with designer for chat-bot icon on TIna site 

### ✅ Acceptance Criteria 

- [x] TinaGPT deployed to live site

### 📸 Screenshots 

<img width="1472" alt="Screenshot 2024-05-06 at 10 39 44 am" src="https://github.com/tinacms/tina.io/assets/137844305/56cfc1d8-f3dd-4d0d-980c-4d51cdb413f7">
**Figure: 🏡 Home page view with chat-bot icon on bottom right**

<img width="1470" alt="Screenshot 2024-05-06 at 10 39 30 am" src="https://github.com/tinacms/tina.io/assets/137844305/26bf7857-689e-4b91-abcd-3d3571646013">
**Figure: 🦙Speaking to TinaGPT on local version of Tina.io site**

Cc:
