### ISSUE TITLE
💄 Tina.io | Subscription Alert Improvement

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#1753]
### 🩸 Pain

When users subscribe on the Tina.io site, they are faced with a bland, vanilla JS alert with either a success or error message

### 💡 Suggested Solution

Implement a fancier looking modal with the status message 

### 💼 Tasks 

- [x] Get wireframes from designers
- [x] Implement modal 
- [x] Test pass from designers
- [x] Test functionality
- [x] (10/05/24) Refactor to use MailChimp API service 

### ✅ Acceptance Criteria 

- [x] Test pass from designers 
- [x] New refactored service works 
- [x] merged to main

### 📸 Screenshots 

(6/05/24) - Update of modal 
<img width="1447" alt="Screenshot 2024-05-06 at 3 59 44 pm" src="https://github.com/tinacms/tina.io/assets/137844305/4067bbf7-9971-4d70-b2af-1f3ac50c1990">
**Figure: Success subscribe**
<img width="1452" alt="Screenshot 2024-05-06 at 3 59 29 pm" src="https://github.com/tinacms/tina.io/assets/137844305/6cbbd808-a906-48d9-bcb2-1ed2de9ad42a">
**Figure: fail subscribe** 

Cc:

**Comment by joshbermanssw** [comment]
@bettybondoc - test pass ✅
