### ISSUE TITLE
💄 Tina.io | Tina vs Competitors 

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#1773]
As apart of improving the [website user experience ](https://github.com/tinacms/tina.io/issues/1731) the current site fails to put emphasis on why users should pick Tina over other headless CMS 

**Tasks**
- [x] Gather information about current popular headless CMS' 
- [x] Improve on the information currently displayed on the Tina page
- [x] Generate content for the question "Why Tina?"  ^ 
- [x] Update content for Tina vs <Specific CMS> 
- [x] Get designer to approve on the page(s) above ^ 
- [x] Test please (Adam & Uly) 
- [x] Make live on site :)

**Comment by joshbermanssw** [comment]
Content written awaiting approval by Seth
- Content will not be implemented until designers finish homepage redesign

**Comment by bettybondoc** [comment]
@joshbermanssw 

(If this needs a separate issue, please move it to a new one)

- [ ] Implement design based on [Figma Page](https://www.figma.com/design/Jyj0SszjfSBc6Minkl3g1l/Tina.io?node-id=127-4548&t=zMWbcmJgsnGtBlux-1) and [Figma Prototype](https://www.figma.com/proto/Jyj0SszjfSBc6Minkl3g1l/Tina.io?node-id=248-3018&t=5GkSyDdRlE5ZVg1Y-1&scaling=scale-down&page-id=248%3A3017&starting-point-node-id=248%3A3018)
- [ ] Get cropped and colour-corrected logos from Betty
- [ ] Consult with Betty for the mobile view
- [ ] Get final content from Landon
- [ ] Get it checked by Landon, Betty and Adam

Expected Behaviour:

- Desktop - The colour of the logo and the table’s second column will change as we cycle through each item. When you click on a logo, an additional column will be displayed (for multiple comparisons). The carousel will cycle automatically on page load and will stop if you try to select any of the logos.
- Mobile - Multiple comparisons will be disabled on mobile since we do not have enough real estate. All other features will be the same.

<img width="478" alt="image" src="https://github.com/tinacms/tina.io/assets/33026270/f65947ea-98ae-4443-9dd0-ddb8833ab09f">

**Figure: Tina vs Competitors**

**Comment by bettybondoc** [comment]
@joshbermanssw 

As per my conversation with Jayden, we could maximise the space by making the default cycles in threes instead of two columns

Additional Tasks:
- [ ]  Discuss the alternate default behaviour with Betty when you're working on this issue

![image](https://github.com/tinacms/tina.io/assets/33026270/855ee3d1-0811-45f3-ba15-2ca296fa3d19)
**Figure: Tina vs Competitors - Alternate Default Behaviour**
