### ISSUE TITLE
✨ Tina.io | Google Analytics for Ad Conversion Tracking

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#1784]
cc: @sethdaily 

As per email `Tina.io - google analytics for ads conversion tracking` 

- [x] Add a google tag to the 'try it now' button to track clicks 
- [x] Same for the 'Schedule a demo' 
- [x] Same for 'copy npx command' 

**Tasks**
- [x] Create new GTM account for Tina.io site
- [x] Implement to tina.io site header 
- [x] Track to buttons 
- [x] Get activity showing up in Google Analytics

**Comment by joshbermanssw** [comment]
Updated - have tag manager respponding to tags firing - need to connect this to google analytics

**Comment by joshbermanssw** [comment]
![Screenshot 2024-05-24 at 10 39 24 am](https://github.com/tinacms/tina.io/assets/137844305/e238044e-053c-4b69-bcce-cfd9332699d2)
**Figure: Using Google Tag Manager Preview to ensure tags are fired on site** 

![Screenshot 2024-05-24 at 10 39 05 am](https://github.com/tinacms/tina.io/assets/137844305/6d4320d0-d067-43fe-8c72-8fad3251401b)
**Figure: Tags created**
