### ISSUE TITLE
✨ Try the editor - make it friendly and interactive

### ISSUE THREAD

**Issue by sethdaily** [tinacms/tina.io#1788]
## 🩸 Pain

When I first find tina.io, I will probably click on the 'try the editor button'
Then I can play with tina on that test page, but the content on that test page isn't super helpful.

Test page: https://quick-edit-demo.vercel.app/admin#/~

Home page:
![image](https://github.com/tinacms/tina.io/assets/130118701/447cfc05-6c08-47fc-9a2a-4e56ae45ca73)
**Figure: Here is the button I click to get to that demo**

## 💡 Suggested Solution
Change from:

### Welcome to the Tina Starter

This project is set up to show you the basics of working with Tina. You're looking at the landing page, which pulls content from content/pages/home.md, components from components/blocks, and puts them all together in pages/[filename].tsx, all based on a config tina/config.tsx.

to

##### Editors

Click this box to start editing it. You will see the matching field appear in the left sidebar for you to make changes. The edits will show in this live preview. In that left panel, you can also navigate around the page to change what you are editing (or just click a component here in the preview, like you did before). Clicking 'Save' won't do anything in this demo - but on your site it will save the changes immediately or send an approval request to your team for review.

##### Developers

This project is set up to show you the basics of working with Tina. You're looking at the landing page, which pulls content from content/pages/home.md, components from components/blocks, and puts them all together in pages/[filename].tsx, all based on a config tina/config.tsx.

## 💼 Tasks 

- [x] add components for the new headings and text boxes
- [x] update the copy

### ✅ Acceptance Criteria 

- [x] It's test passed by Landon and Seth

Cc: @scottgallant

**Comment by joshbermanssw** [comment]
<img width="1469" alt="Screenshot 2024-05-27 at 11 55 50 am" src="https://github.com/tinacms/tina.io/assets/137844305/cf177335-7b0a-4add-a4e5-5b20a7fe9d45">

Content update
