### ISSUE TITLE
✨ Tina.io | press kit publicly downloadable

### ISSUE THREAD

**Issue by landonmaxwell** [tinacms/tina.io#1789]
### 🩸 Pain
The Tina logo & brand assets currently online are hosted through Scott's personal google drive: https://tina.io/press/

### 💡 Suggested Solution
Replace the link with the SSW Sharepoint link: [TinaCMS](https://sswcom.sharepoint.com/:f:/r/sites/SSWDESIGN/Shared%20Documents/General/1-SSW-Logos/TinaCMS?csf=1&web=1&e=vL13Cy)

### 💼 Tasks 

- [x] 1. Replace the link

### ✅ Acceptance Criteria 
- [x] Link is replaced
- [x]  Link is accessible publicly (e.g. anyone can download, even if not signed in

### 📸 Screenshots 
![image](https://github.com/tinacms/tina.io/assets/78135895/2d82e88a-98aa-463a-a2fe-8ea7bb4c07a3)

**Comment by Marxoz** [comment]
@leahy268 Made some changes but still not working

**Comment by Marxoz** [comment]
@leahy268 made some more changes, needs testing from Tina.io side

**Comment by joshbermanssw** [comment]
Done and live
