### ISSUE TITLE
✨ Homepage - Speak with an Expert section

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#1804]
### 🩸 Pain

The new design for the homepage has a section that allows users to speak to a 'Tina Expert'. We dont have a way for users to schedule a call with any Tina Expert Developers 

### 💡 Suggested Solution

Identify who will be the chosen contact and create a hubspot for that person 

### 💼 Tasks 

Refer to comments re: tasks from Betty

### ✅ Acceptance Criteria 

- [x] users can contact the new technical contact 

### 📸 Screenshots 

Cc:

**Comment by bettybondoc** [comment]
@joshbermanssw 

(If this needs a separate issue, please move it to a new one)

Talk to an Expert section on the Homepage
- [ ] Implement design based on [Figma Page](https://www.figma.com/design/Jyj0SszjfSBc6Minkl3g1l/Tina.io?node-id=127-4548&t=zMWbcmJgsnGtBlux-1) and [Figma Prototype](https://www.figma.com/proto/Jyj0SszjfSBc6Minkl3g1l/Tina.io?node-id=248-3018&t=5GkSyDdRlE5ZVg1Y-1&scaling=scale-down&page-id=248%3A3017&starting-point-node-id=248%3A3018)
- [ ] Consult Betty for mobile view
- [ ] Get it checked by Betty and Adam

<img width="476" alt="image" src="https://github.com/tinacms/tina.io/assets/33026270/e602b4b9-d481-43fa-89f0-213fecab0c60">

**Figure: Talk to a Tina Expert**

**Comment by joshbermanssw** [comment]
Doen and live
