### ISSUE TITLE
✨ Key Features - Homepage Carousel 

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#1805]
### 🩸 Pain

The current key features boxes arent the best looking, and they are located quite far down the page. 

### 💡 Suggested Solution

Refer to the revamped homepage to implement the carousel styled key features box and move location up. 

[Figma Mockup](https://www.figma.com/proto/Jyj0SszjfSBc6Minkl3g1l/Tina.io?node-id=248-3018&t=esyxMgKmsNVIlFfr-1&scaling=scale-down&page-id=248%3A3017&starting-point-node-id=248%3A3018)

### 💼 Tasks 

- [x] Create carousel styled component for the CMS 
- [x] Ensure it is automatically scrolling vertically (look at react-slick) 
- [x] Replace current feature boxes
- [x] Add GTM tags to each individual new feature block (refer to #1802)
- [x] Implement and Test 

### ✅ Acceptance Criteria 

- [ ] Test passed by designers and product owner 

### 📸 Screenshots 

Cc:

**Comment by bettybondoc** [comment]
Additional Tasks:
- [ ] Consult with Betty for the mobile view
- [ ] Get final copy/GIFs from Landon

Expected Behaviour (See https://webflow.com/)
- Desktop - Carousel will cycle through each item automatically. When a user hovers over an item, the carousel stops. Clicking on an item will open a new tab.
- Mobile - All the items will be displayed at once (no hovering).

<img width="475" alt="image" src="https://github.com/tinacms/tina.io/assets/33026270/7eeca86a-d40c-4ac7-84ca-90dc4c2a8951">

**Figure: Key Features**

**Comment by joshbermanssw** [comment]
Awaiting GIFs still

**Comment by Marxoz** [comment]
@landonmaxwell to supply @joshbermanssw with the GIFs

**Comment by joshbermanssw** [comment]
Update - code has been approved, content not yet finished. Awaiting 2 more animations
