### ISSUE TITLE
✨ Tina.io - Navigation Bar Modifications  

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#1806]
### 🩸 Pain

Currently there are a few buttons that are located around the site (i.e CTA's) which should be moved to the navigation bar to ensure they are always shown (as nav bar is sticky). 

### 💡 Suggested Solution

Follow the re-designed version of the navigation bar and include all relevant items.

[Figma Mockup](https://www.figma.com/proto/Jyj0SszjfSBc6Minkl3g1l/Tina.io?node-id=248-3018&t=esyxMgKmsNVIlFfr-1&scaling=scale-down&page-id=248%3A3017&starting-point-node-id=248%3A3018)

### 💼 Tasks 

- [x] Implement Figma nav bar 
- [x] Test pass with product owner and designer 
- [x] Tina Cloud in nav bar links straight to TInaCloud Site 
- [x] Keeping pricing (as model shows) 

### ✅ Acceptance Criteria 

- [x] The new navigation bar resembles that test passed by Adam in the figma mockup 

### 📸 Screenshots 

Cc:

**Comment by bettybondoc** [comment]
@joshbermanssw 

(You can move this to a new issue if it needs to be separate)

Email Subscription Modal
- [ ] Implement Feedback Messages (success, error, already subscribed)
- [ ] Consult designer for mobile view  

<img width="477" alt="image" src="https://github.com/tinacms/tina.io/assets/33026270/3113c800-67fa-4db3-998c-d865306bb44e">
**Figure: Email Subscription Modal**

**Comment by bettybondoc** [comment]
@joshbermanssw

As per my conversation with Jayden, we could make some enhancements to the top bar design to improve the visual hierarchy:
- Make the Nav more prominent with the light background
- Right-align the text

- [ ] Discuss the design enhancements with Betty when you're working on this issue

![image](https://github.com/tinacms/tina.io/assets/33026270/2476ae03-7947-4483-a3e3-c981750eb16a)

**Figure: Top Bar - Approved Design**

![image](https://github.com/tinacms/tina.io/assets/33026270/f470f1e7-4f0e-4b05-9c44-dc7c154ff078)

**Figure: Top Bar - Alternate Design**

**Comment by joshbermanssw** [comment]
_Note all of this has been test passed by Betty_

<img width="1325" alt="Screenshot 2024-05-31 at 5 59 04 pm" src="https://github.com/tinacms/tina.io/assets/137844305/a37072c5-63c0-48b5-88f1-bb92deb0e75e">

**Figure: New Nav Bar!**

<img width="1508" alt="Screenshot 2024-05-31 at 5 13 55 pm" src="https://github.com/tinacms/tina.io/assets/137844305/f894ca24-bd9a-4f76-81d0-248a91aeb1c7">

**Laptop view of Modal**

<img width="772" alt="Screenshot 2024-05-31 at 5 16 22 pm" src="https://github.com/tinacms/tina.io/assets/137844305/56b4ed5b-926f-44a8-a7dd-1fb8440ff4d8">

**Tablet view of Modal**

<img width="365" alt="Screenshot 2024-05-31 at 4 27 35 pm" src="https://github.com/tinacms/tina.io/assets/137844305/caf75ec5-626b-4e15-964f-ebb93b923af3">

**Phone view of Modal**

**Comment by bettybondoc** [comment]
Hi @joshbermanssw 

As per our conversation, the screenshots for tablet/mobile don't seem to be the latest ones we have worked on together last Friday:
- [ ] Mobile - Please make the top image rectangle, same with the tablet view
- [ ] Mobile -  Please make title text smaller
- [ ] Mobile/Tablet - Please add rounded, opaque background for the close icon

Thanks! :)

**Comment by joshbermanssw** [comment]
Done & Live!
