### ISSUE TITLE
✨ Epic | Merch store epic

### ISSUE THREAD

**Issue by wicksipedia** [tinacms/tina.io#1807]
We want to be sell our awesome Tina merch on the website.

Options:
1. Use Stripe (free since we already use it) - https://vercel.com/guides/getting-started-with-nextjs-typescript-stripe
2. Use Shopify (cost)

```[tasklist]
### Tasks
- [ ] Spike - Stripe POC
- [ ] Merch - create collection and list products
- [ ] Payments - add cart
- [ ] Payments - add checkout (Stripe integration)
- [ ] Shipping - who is sending out the orders (add employee responsibility)
- [ ] Order confirmation - decide where the order confirmation is emailed
```

**Comment by wicksipedia** [comment]
not stale

**Comment by tiagov8** [comment]
@isaaclombardssw Reopening this one based on our Design Backlog conversation.

We have removed the Design PBI until the Tina team decides to go with this
