### ISSUE TITLE
💄 Tina.io - Homepage - Hero Section Cleanup

### ISSUE THREAD

**Issue by bettybondoc** [tinacms/tina.io#1808]
### 🩸 Pain
The hero section looks a bit messy and the multiple CTAs could be confusing to a user

### 💡 Suggested Solution
Limit to 2 CTAs and replace GIF with a more punchy one

### 💼 Tasks 
- [x] Update CTAs based on Figma design
- [x] Add a play button on top of the GIF that leads to TinaCMS YouTube channel (See https://buttercms.com/)
- [x] Get updated GIF from Landon

### ✅ Acceptance Criteria 
- [x] Test passed by Landon and Betty

### ➕ More Information
[Figma Page](https://www.figma.com/design/Jyj0SszjfSBc6Minkl3g1l/Tina.io?node-id=127-4548&t=zMWbcmJgsnGtBlux-1)
[Figma Prototype](https://www.figma.com/proto/Jyj0SszjfSBc6Minkl3g1l/Tina.io?node-id=248-3018&t=5GkSyDdRlE5ZVg1Y-1&scaling=scale-down&page-id=248%3A3017&starting-point-node-id=248%3A3018)

### 📸 Screenshots 
<img width="477" alt="image" src="https://github.com/tinacms/tina.io/assets/33026270/f2dc4539-f822-418c-a0be-22d17ae1010b">

**FIgure: Hero Section**

Cc:
