### ISSUE TITLE
💄 Tina.io - Homepage - Trusted By Carousel

### ISSUE THREAD

**Issue by bettybondoc** [tinacms/tina.io#1809]
### 🩸 Pain
Not all of the client logos are included

### 💡 Suggested Solution
Include all of the logos and implement a carousel feature to fit all of them in

### 💼 Tasks 
- [x] Include all logos under Showcase
- [x] Get the cropped/colour-corrected logos from Ken
- [x] Turn the logos into an automatic carousel (See https://webflow.com/)
- [x] Consult Betty for mobile view
- [x] Update the links/Showcase page so that clicking on a logo would lead to the specific client section under Showcase

### ✅ Acceptance Criteria 
- [x] Test passed by Landon, Betty and Adam

### ➕ More Information
[Figma Page](https://www.figma.com/design/Jyj0SszjfSBc6Minkl3g1l/Tina.io?node-id=127-4548&t=zMWbcmJgsnGtBlux-1)
[Figma Prototype](https://www.figma.com/proto/Jyj0SszjfSBc6Minkl3g1l/Tina.io?node-id=248-3018&t=5GkSyDdRlE5ZVg1Y-1&scaling=scale-down&page-id=248%3A3017&starting-point-node-id=248%3A3018)

### 📸 Screenshots 
<img width="479" alt="image" src="https://github.com/tinacms/tina.io/assets/33026270/7fbc984f-4122-4a1f-81ee-e624120effcc">

**Figure: Trusted By Logos**

Cc:

**Comment by joshbermanssw** [comment]
Done and Live
