### ISSUE TITLE
✨ Tina.io - Homepage - Videos Section

### ISSUE THREAD

**Issue by bettybondoc** [tinacms/tina.io#1810]
### 🩸 Pain
We do not have videos on the homepage that quickly explain what TinaCMS is all about

### 💡 Suggested Solution
Include Matt W and Scott's videos on the homepage

[Figma Page](https://www.figma.com/design/Jyj0SszjfSBc6Minkl3g1l/Tina.io?node-id=127-4548&t=zMWbcmJgsnGtBlux-1)
[Figma Prototype](https://www.figma.com/proto/Jyj0SszjfSBc6Minkl3g1l/Tina.io?node-id=248-3018&t=5GkSyDdRlE5ZVg1Y-1&scaling=scale-down&page-id=248%3A3017&starting-point-node-id=248%3A3018)

### 💼 Tasks 
- [x] Implement Video Section
- [x] Get final videos from Landon
- [x] Get it checked by Landon, Betty and Adam

### ✅ Acceptance Criteria 
- [x] Video section resembles the mockup
- [x] Test passed by Landon, Betty, and Adam

### ➕ More Information
Expected Behaviour:
- See https://buttercms.com/
- Clicking on the video would open a lightbox with an embedded YouTube video

### 📸 Screenshots 
<img width="477" alt="image" src="https://github.com/tinacms/tina.io/assets/33026270/089e1ebe-dd56-4e4d-85c4-22058f2d7203">

**Figure: Video Section**

Cc:

**Comment by joshbermanssw** [comment]
cc: @Jord-Gui @JackDevAU 

After looking into this with some help from the CMS team, it turns out that whilst TinaCMS has a work-around for allowing .mp4 files to be imported into the media manager, TinaCloud does not at the moment. Due to this we cannot create a component that supports video files -- **BLOCKED**

**Comment by joshbermanssw** [comment]
Pull request with media - https://github.com/tinacms/tina.io/pull/2011

**Comment by joshbermanssw** [comment]
Live
