### ISSUE TITLE
🐛 Missing Google description

### ISSUE THREAD

**Issue by sethdaily** [tinacms/tina.io#1818]
### 🐛 Describe the Bug
When you Google Tina you want to see an accurate description.
Currently it looks like it's just displaying text from the page.

### 🧑‍💻 Reproduction Steps

1. Google TinaCMS
2. Read

(checked by Gert and Landon)
Hi Josh
Change from

Tina's in-context editor cannot be beaten, we're all in on it. Testimonial avatar. Sean Pearce. March 30, 2023. @tinacms is a ...

To

TinaCMS is an open-source headless CMS for editing websites with Markdown. Integrates with GitHub and many front-end web frameworks.

### 💼 Tasks
- [x] Make the above change
- [x] Verify that this field is editable in TinaCMS for the future]
- [ ] If it's not, add it

### 📸 Screenshots 

![image](https://github.com/tinacms/tina.io/assets/130118701/efd722fc-d4b4-4324-8a4d-c27db83a9d38)
**Figure: Bad**

Cc:
@marxoz @adamcogan @landonmaxwell @camillars

**Comment by sethdaily** [comment]
Done - https://github.com/tinacms/tina.io/pull/1821
The field is editable as desired
