### ISSUE TITLE
✨ Homepage - Customisable Nav bar

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#1822]
### 🩸 Pain

Content editors cannot modify the contents in the navigation bar. This also means external elements (i.e links) in the navigation bar will be hard-coded and are susceptible to breaking

### 💡 Suggested Solution

Make the navigation bar editable with Tina 

### 💼 Tasks 

- [x] Create new Tina component for navigation bar 
- [x] Make new component styled the same as the current navigation bar
- [ ] Test and ensure content editors can modify it 

### ✅ Acceptance Criteria 

- [x] Test passed by designer

### 📸 Screenshots 

Cc:

**Comment by joshbermanssw** [comment]
Live ✅

**Comment by joshbermanssw** [comment]
Test passed by @bettybondoc
