### ISSUE TITLE
🐛 Homepage UI Issues

### ISSUE THREAD

**Issue by bettybondoc** [tinacms/tina.io#1840]
### 🐛 Describe the Bug
UI issues on desktop and mobile view

### 🧑‍💻 Reproduction Steps
1. Go to tina.io on mobile and desktop
2. See UI issues

### 🎯 Expected Behaviour 
Clean UI with enough spacing between elements and consistent alignment/font size

### 💼 Tasks

- [x] Mobile - Add spacing between GIF and heading (see screenshots)
- [x] Mobile - Hero Section - Left-align CTAs
- [x] Mobile - Reduce font size of "Trusted by" (make consistent or smaller than the main heading)
- [x] Desktop - Add spacing between GIF and text (see screenshots)

### ✅ Acceptance Criteria 
- [x] UI issues fixed on both desktop and mobile
- [x] Checked by Betty

### 📸 Screenshots 
![image](https://github.com/tinacms/tina.io/assets/33026270/50a3a2c5-8aa8-486d-8203-dd8b8fcb1097)
**Figure: Mobile - Hero Section**

![image](https://github.com/tinacms/tina.io/assets/33026270/629541ac-0da5-4ba9-af8e-2277bcad99e6)
**Figure: Mobile - Trusted By**

![image](https://github.com/tinacms/tina.io/assets/33026270/9639c055-a676-4175-b2a4-0b977e5d27f5)
![image](https://github.com/tinacms/tina.io/assets/33026270/a85d09c9-b827-46f2-8d9d-df83401bed2e)
![image](https://github.com/tinacms/tina.io/assets/33026270/af3441ed-b6cc-4a32-aa05-942d2a93abc8)
![image](https://github.com/tinacms/tina.io/assets/33026270/b03b6433-5482-4543-9275-faf22c5804c8)
**Figure: Spacing issues**

Cc: @bradystroud @joshbermanssw

**Comment by joshbermanssw** [comment]
✅ Done - checked by Betty and live
