### ISSUE TITLE
💄Hover Descriptions - Tina versus Competitors 

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#1862]
cc: @landonmaxwell 
On the tina versus competitors box, we have the criteria's on the left hand side but users may not understand what they mean.

**Tasks**
- [x] Design mockup for desktop and mobile views
- [x] Get Matt Wicks to write the descriptions for each criteria
- [x] Add a description element to each of the criteria and display on hover 

**Acceptance Criteria**
- [x] Test pass from Landon/Betty 

![Screenshot 2024-06-21 at 4 17 53 pm](https://github.com/tinacms/tina.io/assets/137844305/d5c995c2-97d1-4f4f-b4e1-55cd30c5e338)

**Figure: Location to add unique hover descriptions**

**Comment by joshbermanssw** [comment]
stealing from @isaaclombardssw  (he said its cool)

**Comment by Marxoz** [comment]
Hey Josh,

As per the comment from Isaac in the PR, can we look at covering the title with the tooltip when hovered over?

Something like this:
![Image](https://github.com/user-attachments/assets/a574fc70-d96e-4a95-a3b7-fa4da40b68d1)
Figure: Tooltip over the relevant title. Sorry for the bad design skills 😂

**Comment by Marxoz** [comment]
Blocked - Need Betty to continue

**Comment by bettybondoc** [comment]
cc @Marxoz @wicksipedia @joshbermanssw 

1. Test Please
Click on the links to view the hover feature on Figma

![Image](https://github.com/user-attachments/assets/f6771add-09ea-4446-9756-015a1ad4a0e5)
Figure: [Key Features Tooltip - Mobile Prototype](https://www.figma.com/proto/Jyj0SszjfSBc6Minkl3g1l/Tina.io?node-id=1601-3893&node-type=frame&t=IGpQY9NurXYpDAPY-0&scaling=min-zoom&content-scaling=fixed&page-id=248%3A3017&starting-point-node-id=1601%3A3893&show-proto-sidebar=1&hide-ui=1)

![Image](https://github.com/user-attachments/assets/630f0926-207b-4018-b1be-5b9054646383)
Figure: [Key Features Tooltip - Desktop Prototype](https://www.figma.com/proto/Jyj0SszjfSBc6Minkl3g1l/Tina.io?node-id=248-3018&node-type=canvas&t=IGpQY9NurXYpDAPY-0&scaling=scale-down-width&content-scaling=fixed&starting-point-node-id=248%3A3018&hide-ui=1)

**Comment by bettybondoc** [comment]
Test passed by @Marxoz 

@joshbermanssw, take it away! 🚀

**Comment by joshbermanssw** [comment]
![Image](https://github.com/user-attachments/assets/324f3066-9b39-4616-a54f-dee4cc6fbdc3)

**Figure: Done and Live**
