### ISSUE TITLE
♻️ Upgrade TinaCMS on Tina.io 

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#1926]
cc: @Marxoz @JackDevAU 

**Goal**
Update TinaCMS to 1.6.7 and refactor old logic

**Tasks**
- [x] #1936
- [x] #1937
- [x] https://github.com/tinacms/tina.io/issues/1947
- [x] https://github.com/tinacms/tina.io/issues/1961
- [x] #1960 
- [x] https://github.com/tinacms/tina.io/issues/1981

**Comment by joshbermanssw** [comment]
Closing, all items completed
