### ISSUE TITLE
💄 Tina vs Competitors - Fix logo carousel

### ISSUE THREAD

**Issue by bettybondoc** [tinacms/tina.io#1927]
### 🩸 Pain
The logos  in the carousel are spread apart especially on bigger screens.

### 💡 Suggested Solution
Can we make it not fixed width but adjust to the size of the logo?

### 💼 Tasks 
- [x] Fix logo width
- [ ] Change arrow icon, if possible

### ✅ Acceptance Criteria 
- [x] Test pass from Betty

### 📸 Screenshots 
![image](https://github.com/user-attachments/assets/3f755694-85b7-4eb7-8ba2-ca22800a0946)
**Figure: Logos**

Cc: @joshbermanssw @landonmaxwell

**Comment by joshbermanssw** [comment]
✅ test passed by Betty, we did not change the arrow icon however.

- Added numerous breakpoints (6 now from 3 before) where the larger screens (issue raised by Betty) now show 6 logos instead of 5. 

![Screenshot 2024-07-24 at 9 26 14 AM](https://github.com/user-attachments/assets/f72c78f5-a4a1-4006-98f8-336364c1a9ca)
**Figure: 💄 6 Logos on Large Screen**
