### ISSUE TITLE
✨ Apply Live Editing to Tina Docs 

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#1947]
### 🩸 Pain

Tina docs dont support live editing, making it a pain to edit docs!

### 💡 Suggested Solution

We want to use Tina's shiny visual editing tool!

### 💼 Tasks 

- [x] incorporate useTina in data sourcing
- [x] Wire up data correctly to live editor 
- [x] Replace deprecated \<MarkDownContent\> with \<TinaMarkdown\> 
- [x] Apply correct styling components to \<TinaMarkdown\>
- [x] Make the next and previous fields a reference to the docs collection 

### ✅ Acceptance Criteria 

- [x] Tested and works 

### 📸 Screenshots 

Cc:

**Comment by joshbermanssw** [comment]
Live
