### ISSUE TITLE
💄 Image Layering on the Product Tour Page

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#1999]
### 🩸 Pain
Scrolling down on the [product tour page](https://tina.io/docs/product-tour/) results in this layout where the image and footer overlap.
See screenshot below.

### 💡 Suggested Solution
Image could fade out as we reach the footer OR move behind the footer.

### 💼 Tasks 
- [ ] ask Landon to advise on solution
- [ ] investigate and fix the above styling

### ✅ Acceptance Criteria 
- [ ] image and text no longer awkwardly half-overlap

### 📸 Screenshots 
![Image](https://github.com/user-attachments/assets/cd44f75d-02f0-417a-8695-fd187f74e2df)
**Figure – weird image behaviour**

**Comment by isaaclombardssw** [comment]
Cheers, you're right – looks like this has been resolved. I'll close the issue :)
