### ISSUE TITLE
📝 Docs – Removing False Promises

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2008]
### Context

Run-off PBI from the [LLM doc audit PBI](https://github.com/tinacms/tina.io/issues/1979) about marking old support promises as out of date.

### Tasks

- [x] https://tina.io/docs/migrations/upgrading-to-usetina/ – ~“Support for the legacy props on <TinaCMS> will be removed in the future”. Changed to "are removed in later versions" – confirm with Jack P first.~ mark this page as outdated
  - [x] https://tina.io/docs/tina-cloud/faq/ – “ There will be no cost for small teams to use Tina Cloud while it is in Beta. A fair use policy will be coming soon.” and "Other Git providers may be available in the future." – delete the whole pricing section here.
  - [x] ~https://tina.io/docs/tina-cloud/branching/ – “In the future, we'll build on this foundation and support creating pull requests, merging, and other related workflows.”~ okay to leave
  - [x] ~https://tina.io/docs/tina-cloud/schema-migration/ – incredibly bugged titles, may be an old document~ solved in another PBI
  - [x] https://tina.io/docs/forestry/overview/ – “Previews” mentions Vue; Change to link to https://tina.io/docs/contextual-editing/overview/ re: live-editing ("with react pages") and remove the timeframe about Vue – link to Vue discussion on GitHub.
  - [x] https://tina.io/docs/contextual-editing/vue/ – "This is on our backlog, here is the link"
  - [x] https://tina.io/docs/contextual-editing/overview/ (vue) - leave as is.
  - [x] Vue – check if there's a discussion on GitHub (TinaCMS) for Vue support, make one if not.
  - [x] https://tina.io/docs/frameworks/other/ (nuxt) – remove coming soon heading, "Want your framework supported? Check out these GitHub discussions"
  - [x] https://tina.io/docs/forestry/missing-forestry-features/ – discuss with Matt Wicks how to manage this, and fix anchror tag bug
  - [x] https://tina.io/docs/reference/config/ – in enabling visual editing… “We're in the early stages of adding visual editing support in static mode, check back for more details soon!” – ~remove that quote. Check with Jack P what static mode is and if this doc is useful.~ remove this bottom section
  - [x] https://tina.io/docs/reference/search/overview/ – last section… “only Tina Cloud's search API is supported but we plan to provide alternative providers in the near future” – leave as is.
  - [x] https://tina.io/docs/reference/self-hosted/database-adapter/overview/ – “We also plan to support additional database adapters for common databases in the future.” to "We're considering additional database adapters for common databases in the future, if this interests you let us know – then link to discussion page"
  - [x] https://tina.io/docs/reference/toolkit/fields/ – ~default field plugins | color.. ?? Says “May be external soon” – ~check with Jack P if I can remove this.~ link to a current equivalent.
  - [x] https://tina.io/docs/reference/media/external/s3/ – “We hope to document a framework-agnostic approach soon.” – leave as is
  - [ ] After the improvements are live, retrain the chatbot so it can provide up-to-date info

**Comment by isaaclombardssw** [comment]
Discussed  https://tina.io/docs/migrations/upgrading-to-usetina/ and https://tina.io/docs/reference/config/ with Jack P.

The first as a document is all depreciated – should be marked as such.

The problem section in the second ("Visual Editing") is outdated and covered by earlier sections of the docs – to be removed.

**Comment by isaaclombardssw** [comment]
Asked Matt about https://tina.io/docs/forestry/missing-forestry-features/  – the whole forestry migration section could potentially go (forestry is no longer an available software).

For not, I'm marking this page as being no longer updated.

**Comment by isaaclombardssw** [comment]
Re: https://tina.io/docs/reference/toolkit/fields/, appears it's an old version of [this page](https://tina.io/docs/extending-tina/custom-field-components/#default-field-plugins) which we do have in the ToC currently, so decided on linking them with a warning.

**Comment by isaaclombardssw** [comment]
Done – these changes have been merged.
