### ISSUE TITLE
✨ Tina /about page

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#2021]
cc: @Marxoz @landonmaxwell 

### Description

For NDC Copenhagen we have a QR code which forwards users to a tina.io/about page. However we do not have this page yet.  

### 💼 Tasks 

- [x] Create new /about page 

### ✅ Acceptance Criteria 

- [x] Test passed by Landon

**Comment by isaaclombardssw** [comment]
Currently blocked on this as I'm waiting to get an idea of the layout.

**Comment by isaaclombardssw** [comment]
Feedback from Betty and Landon.

![Image](https://github.com/user-attachments/assets/f1864ed8-06f8-4731-a57f-5e76eb1a6c8c)

- [ ] Re-size and re-space the images as per the poster.
- [ ] Add subtitle in "grey" under title.
- [ ] Wider video on mobile.
- [ ] Center title and subtitle.
- [ ] Inter font for subtitle.
- [ ] Black or grey body (find the accent colours).

**Comment by isaaclombardssw** [comment]
Betty and Landon want to expand on this (even after the first review) so currently waiting on design decisions. The current version could be used if necessary.

**Comment by isaaclombardssw** [comment]
This has flown over into [this PBI](https://github.com/tinacms/tina.io/issues/2067) as well, since further changes and a mockup were provided following the initial bit of work outlined in this PBI.
