### ISSUE TITLE
✨ Whats New - Tina Cloud and TinaCMS

### ISSUE THREAD

**Issue by Marxoz** [tinacms/tina.io#2022]
We want linkable pages to show whats new with TinaCMS and TinaCloud 

Create pages for 
- What's new with TInaCMS
- What's new with Tina Cloud

**Tasks**

- [x] Create collections for TinaCMS updates and TinaCloud updates 
- [ ] Create 2 pages, one for tinacms updates and one for tinacloud updates
- [ ] url to be "tina.io/whats-new/tinacms" and "tina.io/whats-new/tina-cloud"
- [x] query content on these pages similar to how the blog pages works (use graphql) 

Fields for collections:
-Version number
-Date Released
-Body

**Comment by joshbermanssw** [comment]
Live. 

![Image](https://github.com/user-attachments/assets/eb8789d9-30ec-4918-8e27-f9b4050c9547)

**Figure: /whats-new/tinacms route**
