### ISSUE TITLE
💄 Button Rework

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#2037]
cc: @bettybondoc

### 🩸 Pain

Currently alot of the components we create use the buttons created and improved upon during before our time at tina - sometimes they dont match the styling we want

### 💡 Suggested Solution

improve the flexibility of the buttons, work with a designer.

i.e on the pricing page, we want perhaps a variant or option for buttons to be full length 

### 💼 Tasks 

- [ ] Designer to come up with design
- [ ] Designer to add to design library
- [ ] Developer to up date solution to use button component from design library

### ✅ Acceptance Criteria 

- [ ] @bettybondoc approves button designs and implementations

### 📸 Screenshots 

Cc:
