### ISSUE TITLE
💄 Spacing Consistency in Headers

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2115]
### 🩸 Pain
We're not sure what style we're going for, as some headings have quite a large gap underneath them before the content, and others do not.

Flagged by Betty.

### 💡 Suggested Solution
Work with a designer on making the spacing under headings consistent.

### 💼 Tasks 
- [ ] Designer to come up with standard
- [ ] Add to Design Library
- [ ] Developer implement changes to all headings

#### Larger padding
![Image](https://github.com/user-attachments/assets/891e30a4-a786-495b-bcf2-5b5f2fa470a5)
![Image](https://github.com/user-attachments/assets/da3015a1-4352-46d0-b2bc-9cb802811015)

#### Thin padding

![Image](https://github.com/user-attachments/assets/12110b1a-2210-4f2a-a8ac-14b33bca6db6)

**Comment by isaaclombardssw** [comment]
That would be great imo
