### ISSUE TITLE
🐛 Event Component – Inconsistencies in the Date Depending on Local Machine!

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2129]
### 🐛 Describe the Bug
It was identified (@bradystroud) that event component dates set by the Tina UI were being converted to UTC from the entered time (i.e. probably Australian time). They then get converted back on render to the users local time (such that two people might have different displayed dates **and** the chip marking the event as "live" or "done" may be inaccurate **and** the dates might differ from the event website).

At the same time (11am on Friday, Aug the 30th AEST)

- Specifically for NDC Copenhagen, on my Laptop the event was stated to be going from the 26th to the 30th and is "live" (true).
- On Brady's laptop the event was stated to be going from the 25th to the 29th and was "done" (not true).

### 🎯 Expected Behaviour 
We have some options...

> As an example, we are gonna use Copenhagen – finishes on 30th at 6pm
>  
> Option 1 – user enters event datetime in event timezone (enter 30th at 6pm)
> Easiest for users
> ✅ Users will save the date + time they see on the events website – no maths phew
>  
> E.g. if the website says the event finishes at 30th 6pm, that is what they enter, regardless of where they are.
> They will also enter a datetime offset from UTC to the events timezone (e.g. Copenhagen +2 hrs)
>  
> Option 1.5 – Option 1 but no timezone field
> use magic to get timezone from location
>  
>  
> Option 2 – Enter (31st at 4am)
> ❌ Seth doing maths – not good, risky bizness
>  
> Option 3 – enter raw string, not date
> No maths for anyone
> How will we do the DONE/LIVE indicator?

\- Brady

### 💼 Tasks
- [x] Add time field to the event schema.
- [x] Ensure date is being saved as a constant, known value (ex. UTC unaffected by local timezone).
- [x] Add a date-time offset to the events schema.
- [x] Use the offset and saved date to generate the LIVE/DONE chip.

### ➕ More Information

As for the implementation – currently (suspected), when users enter a date it will be converted **from their local time to UTC**.
When rendering the page, **the stored UTC time is converted to their local time**, and local time is used for comparison.
No indication to users of what to enter, outside of "start date" and "end date".

Cc:

**Comment by isaaclombardssw** [comment]
Done, to be reviewed as per #2147

**Comment by isaaclombardssw** [comment]
Implemented, but extra TinaCMS fields can be made better – https://github.com/tinacms/tina.io/issues/2173
