### ISSUE TITLE
🐛 Broken Link in tina io documentation

### ISSUE THREAD

**Issue by Ben0189** [tinacms/tina.io#2132]
### 🐛 Describe the Bug
Broken link in this documentation [page](https://tina.io/docs/tina-cloud/schema-migration/), under "The new defineSchema API" section, click on RFC discussion and latter portions.

### 🧑‍💻 Reproduction Steps
As per bug description above 

### 🎯 Expected Behaviour 
- A working link / updated documentation

### 💼 Tasks

- [x] Read through this documentation page 
- [x] Fix the broken link  

### ✅ Acceptance Criteria 
- [x] Link should bring user to the right place
