### ISSUE TITLE
💄 Docs - Update Home navigation

### ISSUE THREAD

**Issue by jeoffreyfischer** [tinacms/tina.io#2157]
### 🩸 Pain
On https://tina.io/, the navigation to Home is inconsistent:
- from most pages, the navigation to Home is done via the lama icon (top-left corner)
- from the Tina Docs page https://tina.io/docs/, the navigation to Home is done via the "Home" button

### 💡 Suggested Solution
On the Tina Docs page, use the existing lama icon (top-left corner) as the Home button, and remove the "Home" button

### 💼 Tasks 
On the Tina Docs page https://tina.io/docs/:
- [ ] change the lama icon's navigation to go to https://tina.io/
- [ ] remove the "Home" button

### ✅ Acceptance Criteria 
- [x] the lama icon's navigates to https://tina.io/
- [x] the "Home" button has been removed

### 📸 Screenshots 
![Image](https://github.com/user-attachments/assets/8b05e28a-45e8-4f80-af50-c130ac474084)
**Figure: On most pages, the navigation to Home is done via the Lama icon**

![Image](https://github.com/user-attachments/assets/63ad2a84-49b6-4d0e-abe1-312cd6e82597)
**Figure: On the Tina Docs page, the navigation to Home is done via the "Home" button**

**Comment by joshbermanssw** [comment]
will start after https://github.com/tinacms/tina.io/pull/2155 is live :)

**Comment by joshbermanssw** [comment]
✅ Done and live, this prompted a re-design of the actual docs itself. The benefit of making the navigation bar consistent with other pages was to provide a more seamless experience for users when switching to the docs. So we appleid this concept to the remainder of the docs, using styling that is seen throughout the remainder of the site, such like
- background gradient
- glass box effects
- pill shaped buttons 


![Image](https://github.com/user-attachments/assets/02938bc6-6380-4ed5-b3db-70d99e3229a6)
