### ISSUE TITLE
✨ Key Features | Homepage Carousel

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#2165]
cc: @bettybondoc @landonmaxwell 

We had this awesome re-design of the tina.io homepage when we started working on it - https://www.figma.com/design/Jyj0SszjfSBc6Minkl3g1l/Tina.io?node-id=399-5400&node-type=FRAME

however we had one component that was never properly built and deployed live

This is the 'Key Features' component

**Tasks**
- [ ] Implement 
- [ ] Re-organise home-page according to figma

**Acceptance Criteria**
- [ ] test passed by betty
- [ ] feature live 
- [ ] homepage looking swanky

**Comment by joshbermanssw** [comment]
Closing as i didnt realise this was a duplicate of https://github.com/tinacms/tina.io/issues/1805
