### ISSUE TITLE
📝 Docs Table of Contents – Major Re-Order Of Docs Pages

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2185]
### Pain 🩸 

While learning about Tina and contributing to Tina.io, understanding the CMS was one of the most complex parts.

And NOT because the CMS is a uniquely complex piece of software.
Going through the docs, it's not immediately clear (or clear for some time) what information is tied together, why it's ordered in this way, and how it's related. 

### Tasks

- [ ] Remove the "Core Concepts" section and "Further Reference" sections – distribute submenu's to other sections.
- [ ] A "Content Modelling" or "Content Schema" section should be added to contain field types, schema, etc. etc.
- [ ] Most of "Schema" submenu in "Further Reference" can move in the above section – i.e. extracted out of that subment. (which removes a layer of nesting and exposes a lot of really key info).
- [ ] Move Further Reference | Media to its own major menu item, closer to the top of the table of contents. @wicksipedia from #1946 

TBC and more to be discussed 😄 

### More pain points (rant)

For instance, the `ui` field. It can be a field of field types and also collections. Each field type has a unique set of props that can be passed into here as config, with some crossover.
It's not immediately clear that there's a distinction here, extra nuance etc., and it's described [early on](https://tina.io/docs/extending-tina/overview/), [later on for collections](https://tina.io/docs/reference/collections/), in each field definition (ex. [datetime](https://tina.io/docs/reference/types/datetime/)). All in separate places with different info.

The ordering is also bad – niche guides like the [migrating from forestry section](https://tina.io/docs/forestry/overview/) (Matt wicks mentioned it's unlikely to be used) are prior to key information like [the typedefs](https://tina.io/docs/reference/schema/) and contents of the [tina folder](https://tina.io/docs/tina-folder/overview/).

The menu grouping is misleading – the final reference section contains info that should really exist in other menu groups and I need to hunt for that information. For example the [docs pages on the content API](https://tina.io/admin/index.html#/~/docs/graphql/overview/) should really exist in the "Querying Content" menu item.

Maintaining the docs will also become easier if all the details of a certain topic are grouped up.

**Comment by isaaclombardssw** [comment]
Adding in further thoughts as they come...

- the FAQ section in the intro is a lot of information before you've even really looked at the tool. IMO it should be a **large orange menu item**, but unlike the others it should just be a link.

**Comment by isaaclombardssw** [comment]
"Overview" used as a title is non-descript when I'm looking for specific info.

For example https://tina.io/docs/data-fetching/overview/ has all the tina client function info, users will want that info fairly often but it's not obvious where it is from the table of contents.

**Comment by isaaclombardssw** [comment]
When you go to the docs (ex. https://tina.io/docs/) all the table of contents menu's are open.

Something like the [Sanity docs](https://www.sanity.io/docs/sanity-studio) (not that they they're amazing) start with them all closed, and as they're also well grouped it's easier to find the type of content you're looking for.

**Comment by isaaclombardssw** [comment]
Bit of a brain dump on that one – not sure what's useful.

**Comment by Marxoz** [comment]
[Docs-Nav-Bar-Sections.md](https://github.com/user-attachments/files/17125267/Docs-Nav-Bar-Sections.md)

For a MVP, Go through sections in above file and find the best structure for the documents.

We can then add and perfect it as a next step

**Comment by isaaclombardssw** [comment]
Reopening this, I have some extra time and am invested in improving the developer experience here :)
