### ISSUE TITLE
✨ Whats New Page Update + Footer Fix

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2189]
From Daily... @landonmaxwell @joshbermanssw 

### 💼 Tasks 

- [x] "See changelog on github", not "see more" on the what's new pages
- [x] "See newsletters" button below this
- [x] Repeat on both what's new pages.
- [x] Investigate why footer links can't be CTR+CLICKED (mac).
- [x] Removing the "Full changelog" link from tinacloud what's new page (private repo, shouldn't be included).

**Comment by joshbermanssw** [comment]
Also adding task from email

- [ ] Please update the panels to have the white gradient on the What's New pages

**Comment by joshbermanssw** [comment]
✅ done and live
