### ISSUE TITLE
➖ Removing Dependencies – Airtable

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2215]
### Pain

Dependabot flagged the dependency 'Airtable', which is used in the file `pages/api/feedback.ts` – this isn't referenced anywhere else and I believe the form is no longer used.

### Tasks

- [x] Ask Scott if this is an account/service we still want to use (optional)
- [ ] Add logging to the feedback function to mark outgoing requests in vercel, then monitor over a period to see if the service is used (optional)
- [ ] Remove the file and test OR if we want to use it, upgrade the package to 0.12.2 and update code

**Comment by isaaclombardssw** [comment]
I've asked @jeffsee55 about this one, it's unlikely this package is being used (possibly used a couple of years earlier by marketing staff) – we're going to try removing the file + package.

**Comment by Marxoz** [comment]
As per our discussion, please go ahead removing the file and the package
