### ISSUE TITLE
💄 Old Docs / Site Versions – Notification Bar

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2234]
### 🩸 Pain
We're getting issues from people seeing [old doc versions ](https://pre-beta.tina.io/docs/plugins/toolbar-widgets/)ex. #2231 – these pages should be clearly marked as out of date and link to the current site.

### 💡 Suggested Solution
Add a notification bar at the top of old versions of the docs, that directs users to the current site.

### 💼 Tasks 
- [x] Designer to mock up banner
- [x] Designer to add to design library
- [x] Investigate how the legacy deployments can be edited.
- [ ] For each of the 3 legacy deployments, add a banner marking it as outdated, and link to the current docs (hard coding is alright, as this code doesn't need to be maintained).

### ✅ Acceptance Criteria 

- [ ] It's clear when you're on a legacy version of the site.

**Comment by bettybondoc** [comment]
cc @Marxoz @landonmaxwell @joshbermanssw @isaaclombardssw @bradystroud 

Hey team,

I was thinking we can reuse the existing design for the notification bar on tina.io for consistency

UX question:

1. Where should the link direct users?
2. Do these archived pages have equivalent counterparts in the latest docs?
3. Or are we just taking them to https://tina.io/docs/?

![Image](https://github.com/user-attachments/assets/5c6cf57d-1853-4e52-8d8a-5168063f7823)
**Figure: Notification Bar**

**Comment by bettybondoc** [comment]
As per conversation with @bradystroud and @joshbermanssw, the link would go to https://tina.io/docs/

@joshbermanssw, reassigning the PBI to you 🚀

**Comment by joshbermanssw** [comment]
Edit on `pre-beta` branch

**Comment by joshbermanssw** [comment]
Couldnt get `pre-beta` branch running due to node versions and package versions
