### ISSUE TITLE
💄 Docs – No unique header styling for tables!

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2242]
### 🩸 Pain
Headers use the regular table row styling.

### 💡 Suggested Solution
Have some different colouring/font weight/etc.

### 💼 Tasks 

- [ ] Design proposal from a designer.
- [ ] Add to Design Library
- [ ] Update styling on tables 

### 📸 Screenshots 

![Image](https://github.com/user-attachments/assets/9baad61f-f4b9-4caa-bd20-f2f9a7bb2b60)

Cc:
