### ISSUE TITLE
🍱 Updating the Astro Page – Community Video + Blurb

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2243]
### 🩸 Pain
The tina.io [astro page](https://tina.io/astro/) is currently looking a little barren.

### 💡 Suggested Solution
Let's add a video from the community to the astro page on Tina.io.

### 💼 Tasks 
- [x] watch the video https://youtu.be/5Opvp6z1uSc
- [x] comment under the video and tweet with personal account
- [ ] ~comment under the video and tweet with the TinaCMS account~ blocked by account issues, I'll leave this one for the email task.
- [x] embed the video with a short blurb into the [astro page](https://tina.io/astro/), with the [about page](https://tina.io/about/) video component.

Cc: @joshbermanssw

**Comment by isaaclombardssw** [comment]
Waiting on SysAdmins for access to the tinacms accounts

**Comment by isaaclombardssw** [comment]
This has been completed on #2254, just waiting to merge.
