### ISSUE TITLE
♻ Refactor – Remove `Guides` stuff

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2251]
### Pain

We've removed the Guides part of the website into the docs, but there still exists guide-specific code.

### Solution

Try and nuke the code relating to guides.

### Tasks

- [x] Delete `utils/guide_helpers.ts`
- [x] Delete `utils/fetchGuides.ts`
- [x] Delete `components/DocumentNavigation/DocsHeaderNav.tsx`
- [x] Test

Cheers 🦙

**Comment by joshbermanssw** [comment]
Done and live
