### ISSUE TITLE
✨ GraphQL and DataLayer old

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2259]
### 🩸 Pain

There's a story here.

We removed the graphQL package and associated code – after doing some research and finding no related code to it.

BUT when we removed it, we were notified by some users that there's actually a 'Tina Playground' at https://tina-gql-playground.vercel.app/object-list-templates

It's a funny program, and it's not obvious if we have access to the code to change it.

### 💡 Suggested Solution
As per my conversation with @Marxoz, will will depreciate the old playground.

### 💼 Tasks 

(Discord)
- [x] Reply/notify users on Discord that we will be depreciating the old playground.
- [ ] Get feedback on what they like that's missing on the current one OR why they don't want to play around locally.

(Tina.io)
- [x] Remove the old GraphQL packages and the related API file.

### 📸 Screenshots 

Cc:

**Comment by isaaclombardssw** [comment]
I'll need @BrookJeynes to help me out with this one.

**Comment by isaaclombardssw** [comment]
#2263 can be reviewed and merged once users have been notified (removes the code and packages).

**Comment by Marxoz** [comment]
Waiting on @brookjeynes-ssw to contact the single user that was using these packages as part of the playground

**Comment by isaaclombardssw** [comment]
I'm closing this as I've deprecated the package, and it's now blocked by waiting for the single user to reply about it.

An email task exists for us to hear about the feedback properly, if we get a response.

**Comment by isaaclombardssw** [comment]
Removed the old playground links that were still in the docs with #2292 so this should be finished up.

Created a new PBI from the users feedback (Schema is not clear enough) #2302
