### ISSUE TITLE
Move Tina.io off Cloudinary

### ISSUE THREAD

**Issue by Marxoz** [tinacms/tina.io#2262]
We have received an email from Cloudinary that we have reached our Account Quota Limit, with the following information:

> Your Cloudinary account SSW Consulting USA (cloud names: 'forestry-demo', 'ddwkbhs6a'), has passed the quota of your currently selected plan:
294 Credits (131% of plan limit)

@wicksipedia replied with the following:

> Forestry-demo is tina.io
Not sure what the other account is used for.
 
> I assume most of the usage would be on tina.io – recommend to move tina.io off Cloudinary since it uses NextJS and next/image caches images (which diminishes the value of the CDN).

- [x] Investigate whether we can move off Cloudinary

**TASKS**
- [x] https://github.com/tinacms/tina.io/issues/2344
- [x] [⚙️ Change video forms (.MP4, .GIF, ...) to .webm](https://github.com/tinacms/tina.io/issues/2358)

**Comment by ncn-ssw** [comment]
@joshbermanssw 

Progress on this issue was made under https://github.com/tinacms/tinacloud/issues/2348

**Comment by joshbermanssw** [comment]
✅ Done - live

![Image](https://github.com/user-attachments/assets/f874072b-876b-44da-8b77-4e9752903291)
**Figure: Media Synced on TinaCloud**
