### ISSUE TITLE
🐛 Spacing in Docs Header

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2333]
### 🐛 Describe the Bug
Looks like the `Tina Docs` menu heading aligned to the right.

### 🧑‍💻 Reproduction Steps

1. Go to a docs page and open the menu.

### 🎯 Expected Behaviour 
Aligned to the left with a little padding.

### 💼 Tasks

- [ ] Check that I'm not crazy with Betty first.
- [ ] Change the CSS.
- [ ] Also the X to close the menu is within the bounds of the version dropdown (a bit awkward).

### 📸 Screenshots 

![Image](https://github.com/user-attachments/assets/24440450-38af-44cc-9993-c65ed467665b)

Cc:

**Comment by joshbermanssw** [comment]
![Screenshot 2024-11-18 at 4 03 20 pm](https://github.com/user-attachments/assets/013f989b-9247-431f-885d-b062d9de356d)
**Figure: New Header**

![Screenshot 2024-11-18 at 4 05 51 pm](https://github.com/user-attachments/assets/9f2b37f4-ece6-4d62-b4cd-8c688da85066)
**Figure: Old Header**
