### ISSUE TITLE
🚒 Cloudinary -> TinaCloud for asset management

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#2344]
cc: @bradystroud 
As per title we want to be moving from Cloudinary -> TinaCloud for asset management 

**Tasks**
- [x] Move all assets that are queried with `https://res.cloudinary.com/forestry-demo/image/upload/` to local repo 
- [x] Find location that these images are being requested and update the route 
- [x] Test each time an image is changed from res.cloudinary to local storage
- [x] After all assets are moved changed config to point towards using TinaConfig 
- [x] Test with Matt W, Nick C and Gert
- [x] Move all .gifs to .webm due to 
- Excessive file size of GIFs (to improve web page speed and decrease request limits in Vercel) 
- Quality & Limited colour pallet

**Comment by joshbermanssw** [comment]
✅ Done, live and working

 ![Image](https://github.com/user-attachments/assets/c0c65615-a98e-4dac-8b61-0f5791f7c2b4)
**Figure: TinaCloud successfully synced**
