### ISSUE TITLE
🐛 Heading structure - should only be a single h1 per page

### ISSUE THREAD

**Issue by bradystroud** [tinacms/tina.io#2373]
### 🐛 Describe the Bug
Right now the heading hierarchy doesn't make sense.
This is important for SEO and accessibility

![Image](https://github.com/user-attachments/assets/52c3a666-eafd-4799-ad61-67ed6151abab)

### 🧑‍💻 Reproduction Steps
1. Test tina.io on https://adresults.com/tools/heading-tag-checker-check-h1-t-m-h6-tags
2. See that the headings dont make sense

### 🎯 Expected Behavior 
Headings make sense

<details><summary>Details</summary>
<p>

Heading tags are levels in the structure of a web page, with the `<h1>` tag by default serving as the page title. There should therefore only be one `<h1>` tag per web page. Then levels can be created with `<h2>` tags, and sublevels with `<h3>` to `<h6>` tags. `<h1>` and `<h2>` tags should appear on every web page; the usage of `<h3>` to `<h6>` tags is optional. The most important thing is that heading tags are used according to the standard paragraph structure. So for what would normally be paragraph 1.1 and subsection 1.1.1, you respectively use `<h2>` and `<h3>` tags. To give you an idea of what that might look like:

```html
<h1>Title</h1>

<h2>Paragraph 1</h2>

<h2>Paragraph 2</h2>

<h3>Paragraph 2.1</h3>

<h4>Section 2.1.1</h4>

<h3>Paragraph 2.2</h3>

<h4>Section 2.1.2</h4>

<h2>Paragraph 3</h2>
```

In this example the levels are also indicated by indentations, to show you that a \<h1\> tag is never directly followed by a \<h3\> tag.

Source - https://adresults.com/tools/heading-tag-checker-check-h1-t-m-h6-tags
</p>
</details> 

### 💼 Tasks
- [ ] Read and understand https://www.semrush.com/blog/header-tag/
- [ ] Fix heading hierarchy

### ✅ Acceptance Criteria 
-[ ] Heading structure follows 

Cc: 
@Marxoz @bettybondoc

**Comment by landonmaxwell** [comment]
![Image](https://github.com/user-attachments/assets/c3bbc677-07f3-4652-b07b-d5425d8ed3f4)
Figure: Pages that need fixing for only 1 H1

**Comment by landonmaxwell** [comment]
[tina.io_multiple_h1_tags_20241113.xlsx](https://github.com/user-attachments/files/17724446/tina.io_multiple_h1_tags_20241113.xlsx)
Pages with multiple h1 headings

**Comment by isaaclombardssw** [comment]
> Figure: Pages that need fixing - no h1

@landonmaxwell 
Anything on the subdomain "app" .tina.io is TinaCloud – no need for that to be changed I reckon (or ask the Cloud guys if it should be changed)

**Comment by isaaclombardssw** [comment]
@bradystroud @landonmaxwell 

As per our conversations I'm going to add a toggle on each block component to fix the core issue, which allows the editor to set the H1.

Landon and I do think solving this programmatically would be better, but Brady doesn't think there's a reliable solution there.

A lot of docs pages also have duplicated h1's.

### Tasks

- [ ] Add toggles that set top level block headings as either h1 or h2.
- [ ] Headings on docs text fields shouldn't be h1's (there's a title that already accounts for that).

Bumping this up to a 4 as I'll need to add a toggle on a bunch of the ~25 components we have

**Comment by isaaclombardssw** [comment]
Update – I'm going to put this one as blocked for now, need to discuss with Gert + Josh technical feasibility of the options we have

**Comment by isaaclombardssw** [comment]
As per my conversation with @Marxoz and @landonmaxwell – we will go with the toggle approach. No longer blocked.

### Tasks

- [ ] Add a toggle to each block setting the top level title to an H1.
- [ ] Have some block-level visual indicator so editors can identify which block is the H1 block.
- [ ] Account for H1's used in rich text field (make them H2's with the same styling?) on block, blog and doc pages (currently lots of docs have 2 H1's due to this).
- [ ] Check all flagged pages after changes.

**Comment by landonmaxwell** [comment]
Check if this affects AI searchability
