### ISSUE TITLE
💄 Annual Pricing – Layout changes

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2378]
### 🩸 Pain
Betty and Landon have identified a detail with the styling that can be improved, on the annual pricing page.

The size of cards is changing when you swap between annual and regular pricing, which ruins the lines of alignment.

### 💡 Suggested Solution
Add spacing under the {{ COST }}/month label so that the card size is the same and the **buttons are all aligned when annual pricing is selected**.

### 💼 Tasks 

- [x] Adding spacing to monthly pricing cards, under the {{ COST }}/month label (to match height of the text inserted in annual pricing mode).

### ✅ Acceptance Criteria 

- [x] When in annual pricing mode, the card heights are the same as in the monthly mode.
- [x] Buttons are all horizontally aligned in both modes.

### 📸 Screenshots 
![Image](https://github.com/user-attachments/assets/797a79d0-2e56-4cb8-a576-cc0d3cd848a0)
**Figure – annual pricing, larger cards and out of alignment**

![Image](https://github.com/user-attachments/assets/d1c0ae6d-e6dd-4338-9f40-f7ebd77b564a)
**Figure – monthly pricing, all aligned**

Cc: @bettybondoc @landonmaxwell @joshbermanssw

**Comment by joshbermanssw** [comment]
![Image](https://github.com/user-attachments/assets/ed1f2585-7fbd-408d-85b8-5b304fbabcb6)

**Figure: All aligned**
