### ISSUE TITLE
📝 Blocks Field Type Page – Out of Date

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2380]
### 💫 Describe the Issue With the Current Docs
The [blocks field type page](https://tina.io/docs/reference/toolkit/fields/blocks/) – not accessible from the ToC BUT comes up in google results.

Out of date schema definitions, old links in the quote, outdated typedefs and gifs. 

### 📝 Outline the Proposed Change
1. On [block type page](https://tina.io/docs/reference/toolkit/fields/blocks/), the following quote is out of date, and the gif below it.
"For an in-depth explanation of the Blocks field, read our ["What are Blocks?"](https://tina.io/blog/what-are-blocks/?_gl=1*10lo7ym*_up*MQ..*_ga*MTAxNDA1NDk4My4xNzMwMjQyMTQ3*_ga_9R1HHZC8HX*MTczMDI0MjE0Ny4xLjAuMTczMDI0MjE0Ny4wLjAuMTQyNzA1NjExNA..) blog post. To see a real-world example of Blocks in use, check out the [Tina Grande Starter](https://github.com/tinacms/tina-starter-grande)."
{{ OUT OF DATE GIF }}
2. Typedefs and schema configs might be wrong.

### 💼 Tasks

- [ ] Change as per (1) above.
- [ ] Test all typedefs and schema configs on the page, replace with working versions or notify CMS team in unable to get working.

Cc:  checked with @JackDevAU

**Comment by joshbermanssw** [comment]
- [ ] Put a notification/ warning bar for now on the top of the page notifying users that this is out-dated and to go to https://tina.io/docs/editing/blocks (or a more suitable page)
