### ISSUE TITLE
📝 Getting Started – Update the Options

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2392]
### 💫 Describe the Issue With the Current Docs
One of the first pages (and commonly linked to pages) is the ["getting started"](https://tina.io/docs/setup-overview/) page.
This has 4 links, one of which is Migrating from Forestry. 

This is no longer necessary, and is also the perfect place to include a way for people to get in contact if they need help with the setup.

![Image](https://github.com/user-attachments/assets/ce80792d-d645-47b4-89a0-c9ea138129d3)

### 📝 Outline the Proposed Change
1. Change the "Migrating from Forestry" link to "Not a dev? Get in Contact" (or similar link).

### 💼 Tasks

- [ ] Change the button and link.
- [ ] Possibly update the card + button styling for that square.
- [ ] Get any design changes approved by a designer, and Landon.

Cc: @landonmaxwell
