### ISSUE TITLE
📝 New Page – Framework Comparison

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2393]
### 💫 Current Pain of the Site Content
We have a great comparison component that we use with competitors on the homepage.

We want to know how Tina fits with different SSG Frameworks (ex. Next.js, Gatsby, Astro) and make that info accessible to users.

### 📝 Outline the Proposed Change
1. Create a new page called "Choosing the right framework?" – or something similar.
2. Create an intro going over Tina's best recommendation, how flexible it is etc. etc.
3. Use the competitor comparison component "compare box" to what features you can take advantage of in each framework.
(would this be framework features, or Tina features??).
4. Link to each framework page ex. tina.io/astro or tina.io/hugo-cms in some way.
5. Add the new page to the navbar (maybe under resources).

### 💼 Tasks
- [ ] Create the above page.
- [ ] Get the content approved for correctness by Wicksy + Jack P 😱
- [ ] Get the copy approved by landon
- [ ] Link to the page under Resources

### 📸 Screenshots 
![Image](https://github.com/user-attachments/assets/a1ffaae7-adcc-48fe-b04b-7cfc514cb5e8)
**Figure – competitor comparison on the homepage, for reference**

Cc: @landonmaxwell

**Comment by isaaclombardssw** [comment]
Contact Landon or Isaac for chatbot data – might be helpful in deciding what Frameworks to include.
