### ISSUE TITLE
📝 Updating Framework-Specific Pages

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2394]
### 💫 Describe the Issue With the Current Site Content
We have a lot of pages, like https://tina.io/mdx-cms/, https://tina.io/tinacms-contentful-comparison/ and https://tina.io/hugo-cms/ that basically exist for google juice.

They're not fleshed out well, and are a bit inconsistent (some have a CTA, some a FAQ, these weird button cards that look like links and minimal content).

### 📝 Outline the Proposed Change
1. List out these pages.
2. Work with a designer to redesign them, using existing on new blocks. (remove the cards?)
3. Update the content on each page to be current.

### 💼 Tasks

- [ ] List out similar pages, find them in the tina editor or `/content`
- [ ] Work with a designer to redesign them, using existing on new blocks
- [ ] Update the content on each page to be current
- [ ] Check content accuracy with Wicksy
- [ ] Check content with Landon

Cc: @landonmaxwell
