### ISSUE TITLE
🎥 Done Video - Globe Component

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#2410]
cc: @landonmaxwell 

As per request from a user in the TinaGPT bot 

![Image](https://github.com/user-attachments/assets/ec6abee4-4f11-4e86-9535-070c2c5ac798)

**Figure: Done video request**

**Tasks**
- [x] Record Done Video 
- [x] Get Approved by Landon and Gert
- [x] Publish on Tina.io YT!

**Comment by joshbermanssw** [comment]
v1: https://youtu.be/XeYJgskrKAo

**Comment by joshbermanssw** [comment]
Done v2: https://youtu.be/an3Fn0CLNng

**Comment by landonmaxwell** [comment]
Tina branded version on the main channel: https://youtu.be/oSpQkvMEfGI
