### ISSUE TITLE
📝 Docs – Field Plug-In Audit

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2423]
### 💫 Describe the Issue With the Current Docs
There's a bunch of "Field Plugin" type pages linked to here – https://tina.io/docs/extending-tina/custom-field-components#default-field-plugins.

They should be in the ToC somewhere, and there should be actual info on how to use them.

As they're not in the ToC – they've also been missed and some haven't been updated in a number of years.

Josh didn't even know they existed – do we care about making this info available? (one for Jack + Matt)

### 📝 Outline the Proposed Change

1. Go through each https://tina.io/docs/extending-tina/custom-field-components#default-field-plugins
2. Propose changes and examples so each is now correct.
3. Extract this section to it's own doc page – add examples of the concept.
4. Create a submenu for each of the field plugins in the ToC and group this stuff together.

### 💼 Tasks

- [ ] Make changes as above
- [ ] Test each new example in a Tina project
- [ ] Get everything checked by someone – probably Jack (or Matt if he's unavailable) (OR just create the PR if you're not a Tina contributor yet and we'll get it checked for you).
