### ISSUE TITLE
📝 Docs - General Markdown Migration Guide

### ISSUE THREAD

**Issue by Lewkans** [tinacms/tina.io#2438]
Cc: @Marxoz 
### 💫 Describe the Issue With the Current Docs

As per my conversation with Gert, as more migration guides are made for different frameworks increase (Astro, WordPress etc), there should a general markdown migration guide to avoid needing to repeat in each document, where they can be directed to this document.

### 📝 Outline the Proposed Change

- Create a guide that goes over general migration tips for converting markdown from other frameworks to Tina
- Link other migration documentation to this guide

### 💼 Tasks

- [ ] Investigate the format of different markdown from different frameworks
- [ ] Create a guide that encompasses general migration tips
    - [ ] What data we get, and what the schema can look like 
    - [ ] Limitations of the markdowns (what data is lost, what do we need to implement ourselves)
- [ ] Link other migration documentation to this guide

### 📸 Screenshots 

Cc:

**Comment by Marxoz** [comment]
Not high priority until we have a second migration document
