### ISSUE TITLE
💸  Tech Debt – The Compare Box (Hard Coded "Join Table")

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2456]
### Pain 🩸 

The current compare box block has implementation issues, which make the editing experience bad and inflexible.
These are all problems with the boolean "list" (hard coded length) in the "Companies" object in the schema – this controls whether a "Company" satisfies the criteria at a specific index in the criteria list.

1. There can be any number of criteria, but **always** 10 booleans in each companies editor
2. Each boolean in the companies editor is un-labeled
3. Criteria is totally decoupled from the Changing the order or data of the criteria. 
i.e. If you change the criteria order, you need to go into every company and reset the booleans to match.
If you change criteria text, it still has all the old boolean settings in each company object.

See screenshots below for the specific problem.

### Tasks

I've started work on this, to see current solution (using `BeforeSubmit` to reach in and synch values) see the branch... `tina/repo-based-media`. 

- [x] Check with Jack P about data passing between Tina form fields (I suspect this has been made difficult intentionally).
- [x] Come up with a solution + custom components such that... boolean list syncs up to the criteria list in terms of length and label.

### Acceptance Criteria

- [x] Changing the criteria list order makes equivalent changes to the company boolean list.
- [x] Boolean list is labelled based on the criteria.
- [x] Boolean list length matches criteria list length.

### Screenshots 📸 

![Image](https://github.com/user-attachments/assets/3a6723bc-511f-47de-a391-8d327c5d4cf3)
**Figure – we have a list of criteria**

![Image](https://github.com/user-attachments/assets/50bc29ad-2cdf-44e8-bc6c-1ef829c32f77)
**Figure – we have a list of things to compare (e.g. companies) – same level of nesting as the criteria list**

![Image](https://github.com/user-attachments/assets/d9659120-c79d-4b07-b553-b1f27b9a9244)
**Figure – ❌ ❌ ❌ the bad, each thing to compare has a column of booleans to be mapped to the criteria**

**Comment by isaaclombardssw** [comment]
See PR #2439 – proud of this one

**Comment by landonmaxwell** [comment]
[https://outlook-1.cdn.office.net/assets/reaction/heart.png]    Landon Maxwell [SSW] reacted to your message:




[cid:ssw-circle(1)_4c7259a6-23f6-49e5-b933-230ca304562e.png]

Landon Maxwell
SSW Multimedia Specialist/Videographer
Stalk: SSW People<https://www.ssw.com.au/people/Landon-Maxwell?utm_source=emailsignature>   |   Walk: SSW Melbourne<https://www.ssw.com.au/ssw/Company/Offices/?utm_source=emailsignature>   |   Talk: +61 425 360 959<https://www.ssw.com.au/ssw/Company/ContactUs.aspx>
[cid:youtube-icon_b8b5cda9-a973-4973-8763-cf3d4922e060.png] <https://www.youtube.com/c/SSWTV>    [cid:linkedin-icon_b153ac9a-eb66-47d9-9c51-ad20b42b8a0a.png]  <https://www.linkedin.com/company/ssw/>    [cid:x-logo_3eb6d0d3-24fb-487d-a4a7-2e30cddc1ebf.png]  <https://x.com/SSW_TV>    [cid:teams-icon_552803c2-9c44-4267-b563-7fe1a7a0e589.png] ***@***.***>


        TinaCMS, the #1 CMS on GitHub, is now part of the SSW family<https://adamcogan.com/2024/05/15/ssw-purchases-tinacms?utm_source=emailsignature>

________________________________

**Comment by isaaclombardssw** [comment]
Done – see the PR #2439

**Comment by isaaclombardssw** [comment]
Done video – https://youtu.be/USypgIFGMM0
