### ISSUE TITLE
📦  Epic | Tina.io Component Library

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2468]
@Marxoz @landonmaxwell @joshbermanssw  @bradystroud 

### Pain 🩸 

It's impossible to get around the fact that there's a lot of overhead, necessitating the development of new components built with React while creating an application with TinaCMS.

Not everyone has this kind of time or budget. It would be great if the components we build for Tina.io and community components could be collated into some kind of library of preset blocks.

**There's a question to ask here about how much these come pre-styled, or is that onus all on the user (i.e. we just handle the Tina template, general structure, data handing and live editing)**.

### Solution

- [ ] Discuss solution and who/how this should be maintained
- [ ] Discuss how best to release the components
- [ ] Discuss how should these be advertised

**Comment by landonmaxwell** [comment]
"Hero" component:
Changes:
1. Test field to be rich text
2. Custom Margin not working
3. Custom Spacing not working

![Image](https://github.com/user-attachments/assets/2f3f0ff2-6d44-4d1b-9ac8-345f4718bbae)

**Comment by landonmaxwell** [comment]
Additional considerations for this Epic:

- [ ]  Discuss how we audit components

(e.g. Use 1 epic with sub-issues?)

**Comment by isaaclombardssw** [comment]
More notes – making the quote cards, "`Testimonials`", good for release.

1. Create generic version.
2. Image to right.
3. Rename to **card mosaic**.
4. Date is broken currently
5. Image border should have a toggle.
