### ISSUE TITLE
🔌 NPM Package - Recipe Component

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#2476]
cc: @wicksipedia @Marxoz @landonmaxwell @isaaclombardssw 

We want to be able to make working with Tina even easier! So we're going to publish components in our #2468 

This PBI is for creating an npm package out of the Recipe block component 

**Tasks**
- [x] Investigate how NPM packages are created
- [x] Create new repository under the tinacms organisation on GitHub for the component 
- [x] Publish NPM package on private account (or using link locally)
- [ ] Test it works on tina.io
- [ ] Publish NPM package under the TinaCMS account (speak to Wicksy) 
- [ ] Test it works on tina.io
- [ ] Write readme in package to 1) show people what it looks like, and 2) show them how to install it into their tina projects

**Acceptance Criteria**
- [ ] all tasks complete
- [ ] approved by Wicksy and Gert

**Comment by joshbermanssw** [comment]
cc: @Ben0189 @Marxoz 

I dont think this is possible currently with our setup of tina.io. There are issues with global imports of CSS files and it is a known predicament with using the monaco editor with the pages router. see https://github.com/vercel/next.js/discussions/27953#discussioncomment-3978605 and https://github.com/vercel/next.js/discussions/27953#discussioncomment-3978605

**Comment by joshbermanssw** [comment]
NPM package has been created at https://www.npmjs.com/package/recipetinacms?activeTab=code

Repository has been created at [RecipeComponent](https://github.com/tinacms/RecipeComponent)
