### ISSUE TITLE
✨ Pricing - Tier Comparison Table

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#2496]
cc: @bettybondoc 

We want a pricing table underneath the pricing tiers to show a more in-depth analysis of what each tier gets 

<\ADD DESIGN LINK WHEN BETTY FINISHES\>

**Tasks**
- [x] Let betty design
- [x] Implement 

**Acceptance Criteria**
- [x] Approved by Betty, Landon and Gert

**Comment by joshbermanssw** [comment]
Figma mockup: https://www.figma.com/proto/Jyj0SszjfSBc6Minkl3g1l/Tina.io?node-id=1351-9459&node-type=frame&t=Zn0HHY4EW9oELRXo-0&scaling=scale-down-width&content-scaling=fixed&page-id=673%3A2513&starting-point-node-id=1351%3A9459

**Changes:**
- [ ] Created new table component - components/blocks/table/table.tsx & table.template.tsx 
- [ ] Created my own segment of logic, similar to Isaac's in `criteriaMapping()` I have created a PBI to clean up this code and extrapolate into its own class (https://github.com/tinacms/tina.io/issues/2510)

https://github.com/user-attachments/assets/1a8e8ab2-8174-487d-86ef-cae1ca3be94a
**Figure: Scroll Behaviour on < 1200px screens**

![Screenshot 2024-11-25 at 2 17 45 pm](https://github.com/user-attachments/assets/9c949e3c-63ab-49e0-b52b-493de80a8ed5)
**Figure: Laptop+ sized screen view**
