### ISSUE TITLE
✨ Docs - Refactor responsiveness, layout and components

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#2552]
Our current docs implementation has 3 primary issues 
a) The responsiveness is not ideal - when we stretch the screen we see the UI sticks to the left
b) It is old, outdated 
c) It uses ALOT of styled jsx - we want to move towards only Tailwind 
d) components are hard to navigate as a dev

**Tasks**
- [x] Use tailwind to control the primary layout of the docs (i.e a grid system that has a grid for each the left hand nav, middle content, and right hand nav
- [x] set a max screen width 2xl 
- [x] justify the grid in centre 
- [x] replace the old left nav bar with the one used in the docs search page

**Comment by joshbermanssw** [comment]
<img width="1160" alt="Image" src="https://github.com/user-attachments/assets/81d1dc2b-9f99-4a37-a5ad-a769dea44b0c" />

**Figure: Md View**

<img width="709" alt="Image" src="https://github.com/user-attachments/assets/608f616f-6310-457d-995d-3c6cac44c9f4" />

**Figure: Sm View**

<img width="1323" alt="Image" src="https://github.com/user-attachments/assets/5e0471b9-8d00-4c79-be2f-a235f758010b" />

**Figure: Extreme zoom-out w/ Max-width of 2xl**
