### ISSUE TITLE
✨ Footer Navigation - use Tina Collection

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#2656]
Currently the Footer is hard-coded (in two locations due to the page to app router migration)

We want to move the Footer Navigation to be using and editable with TinaCMS

**Tasks**
- [x] Move data to collection (.json style)
- [x] Split up collection by column location in the footer
- [x] Wire up to react component 

**Acceptance Criteria**
- [x] Footer nav is editable with TinaCMS

**Comment by joshbermanssw** [comment]
Done and live
